<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit_advanced_ads_pro
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('AdvancedAdsPro\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \AdvancedAdsPro\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit_advanced_ads_pro', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \AdvancedAdsPro\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit_advanced_ads_pro', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\AdvancedAdsPro\Composer\Autoload\ComposerStaticInit_advanced_ads_pro::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
