<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Advanced_Ads_Pro\\Rest_Api\\' => array($baseDir . '/modules/rest-api/classes'),
);
